baseURL: "http://hasan.baygul.tk"
languageCode: "en-us"
title: "hasan' s blog"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
  spotify: "#"
taxonomies:
  author: authors
